server:
  servlet:
    context-path: /api
  port: 8888
spring:
  config:
    activate:
      on-profile: production-set1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j7d106.p.ssafy.io:3306/doseok?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hive
    password: nh+7&(tUa7p[NYcAae{Sno&LM698=1
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test db;MODE=MySQL;DATABASE_TO_UPPER=FALSE;

logging:
  level:
    org.hibernate.sql: debug
cloud:
  aws:
    credentials:
      access-key: AKIAUBFKRXNYJ266HFAM
      secret-key: 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
    s3:
      bucket= ssafyd106
    region:
      static: ap-northeast-2
---

server:
  servlet:
    context-path: /api
  port: 8889
spring:
  config:
    activate:
      on-profile: production-set2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j7d106.p.ssafy.io:3306/doseok?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hive
    password: nh+7&(tUa7p[NYcAae{Sno&LM698=1
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test db;MODE=MySQL;DATABASE_TO_UPPER=FALSE;

logging:
  level:
    org.hibernate.sql: debug
cloud:
  aws:
    credentials:
      access-key: AKIAUBFKRXNYJ266HFAM
      secret-key: 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
    s3:
        bucket= ssafyd106
    region:
      static: ap-northeast-2